// Generated by admin/setup.html — safe to commit.
// The token below is AES-256 encrypted with the admin password.
window.MC_CONFIG = {
  owner: "gdf0",
  repo: "condo-reminders-private",
  vault: {
    salt: "O9nCBU83jAwfpa7HNgiOgw==",
    iv: "y6VARsOORG16mrmK",
    data: "9abhaaUQLfiGIHcc6K3g0MEhiNACVIIjUNQwYpyloWoyJSYHUFVJ+B4gzzKmTL02aPu31ybo3+yrK5X854n8WYmJ1OsFjI2sMzKwRTJy3Afb2KYzrAAUWljfL8gz9hR51UgGADtgf4b8HS4tzw==",
    iterations: 600000
  }
};
